project:
  type: book
  output-dir: docs

book:
  title: "Palmyra Atoll Data Library User Guide"
  chapters:
    - index.qmd
    - content/about-this-guide.qmd
    - content/basic-concepts.qmd
    - content/data-workflow.qmd
    - content/metadata.qmd
    - content/ezeml.qmd
    - content/metadata-templates.qmd
    - content/other-options.qmd
    - content/resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

