project:
  type: book
  output-dir: docs

book:
  title: "Palmyra Atoll Data Library"
  chapters:
    - index.qmd
    - intro.qmd
    - getting-started.qmd
    - tidy-data.qmd
    
    - part: how-to-ezeml.qmd
      chapters: 
        - set-up.qmd
        
    - metadata-templates.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

