# Welcome! {.unnumbered}

The Palmyra Atoll Data Library (PADL) aims to publish as much data collected at Palmyra Atoll as possible.

Facilitating access to research and its associated data will amplify academic discussions, help other researchers, and further inform the management and policy decisions in Palmyra and other tropical ecosystems.

We are working with the [Environmental Data Initiative (EDI)](https://edirepository.org/), an NSF-supported initiative that provides a reliable, registered, and certified trustworthy data repository with an open-access API. EDI follows a high metadata standard that ensures that your future self and others can utilize data for scientific and other inquiry forms.


### What you need to do
- Read this guide carefully to familiarize yourself with basic concepts on publishing environmental/ecological data.
- Look into the **"Your turn"** section at the end of this guide and see the things and steps you need to have in place to do successfully publish your data.


### Why PADL?

We want a centralized place where scientists and managers can access all data collected at Palmyra Atoll. Data are among the most valuable outputs of research. If no one can access these data, all the data collection is a shocking waste of resources. An open data library allows for aggregating and synthesizing data from different contexts. This is essential to establishing broader ecological knowledge and informing conservation management. Long-term data are crucial to understanding historical patterns and baselines in a changing world. PADL wants to make it easy for scientists to know and access research done at Palmyra in the past.


### Questions?
Please contact XXXX XXXXX


## Credits

This guide borrows heavily from [EDI resources](https://edirepository.org/resources/resources-for-data-authors), [CAP LTER Getting Started Guide](https://caplter.github.io/caplter_ezeml/#getting-started) and [NCEAS coreR curriculum](https://www.nceas.ucsb.edu/learning-hub/core-r). Check out the links and see the complete citation in the reference section.
